### ISSUE TITLE
Docker image available when?

### ISSUE THREAD

**Issue by mariushosting** [remvze/moodist#1]
Is there any time-line for Docker support?

**Comment by Evigami** [comment]
YES! Would love to self-host this...

**Comment by remvze** [comment]
Thanks to @javigomezo, Moodist now has a Dockerfile.

**Comment by remvze** [comment]
Thanks to @javigomezo, Moodist now has a Dockerfile.

**Comment by Melantrix** [comment]
Can you add something like a pipeline to generate new docker images? I think the current image is not updated with the new sounds (on the moodist.app there are 70, while the docker image has 54).

**Comment by mariushosting** [comment]
+1

> @remvze Can you add something like a pipeline to generate new docker images? I think the current image is not updated with the new sounds (on the moodist.app there are 70, while the docker image has 54).

**Comment by remvze** [comment]
@Melantrix Hello! Moodist does have a workflow in place to generate and publish a new image with each new version, but I hadn't released one until now. Enjoy the new sounds!

**Comment by tasty007** [comment]
> @Melantrix Hello! Moodist does have a workflow in place to generate and publish a new image with each new version, but I hadn't released one until now. Enjoy the new sounds!

I would like to publish a new image
