### ISSUE TITLE
How to install on Synology DSM 7

### ISSUE THREAD

**Issue by darkj2k** [remvze/moodist#18]
Anyone can guide me how to install moodist on my DS920+? Thanks in advance.

**Comment by remvze** [comment]
Hey there. [This tutorial](https://mariushosting.com/how-to-install-moodist-on-your-synology-nas/) from @mariushosting might be helpful.

**Comment by darkj2k** [comment]
> Hey there. [This tutorial](https://mariushosting.com/how-to-install-moodist-on-your-synology-nas/) from @mariushosting might be helpful.

Thanks so much. It's truly helpful. :-)
