### ISSUE TITLE
Docker container for ARM hosts - Raspberry Pi

### ISSUE THREAD

**Issue by yebo29** [remvze/moodist#23]
Is there a container for ARM 32/64 bit machines such as the Raspberry Pi, or should I attempt to build one? How do I tag it?

**Comment by yebo29** [comment]
Seems like we'd just need to use the https://hub.docker.com/r/arm64v8/node/ tag/container in the Dockerfile and build off of that.

**Comment by remvze** [comment]
I've just added support for ARM64 architecture. Since it's using Buildx to create a multi-arch image, the tag remains the same as before (i.e., 'latest').

**Comment by yebo29** [comment]
Thank you! ARM64 is perfect.

**Comment by yebo29** [comment]
It worked just fine. Thank you once again!
