### ISSUE TITLE
Shortcuts are not working in the menu

### ISSUE THREAD

**Issue by SuperMeepBoy** [remvze/moodist#27]
New shortcuts to open Pomodoro, Notepad or else in the menu don't seem to work for me.

For example, when I press Alt+P, Pomodoro modal does not open.

**Comment by SuperMeepBoy** [comment]
Follow back : they work but not all the time. I don't know how to reproduce but when I refresh, I can open Pomodoro, Notepad. I can never open Share Sounds modal.

If I open/close them a few times, the shortcuts start not working. It sends be to the bottom of the page, then it goes up a little, etc. No modals open until I refresh. :thinking: 

Do you have that too ?

**Comment by remvze** [comment]
> May I add that using "Alt" for shortcuts is, in my opinion, not a good idea. Alt + N for example does something in Firefox.
> 
> From what I see on other websites, such as Gitlab, "Shift" is a good replacement. So Shift+P could be used for Pomodoro, Shift+N for Notepad. 😊

I agree; I changed them to shift instead.

**Comment by SuperMeepBoy** [comment]
Found where the bug comes from I think. As I wanted to work on accessibility, I enabled my screen reader. Though I disabled it yesterday, it enabled again at startup and it seems that it is doing the bugs.

The only bug now is :
> Shift+Alt+P opens Pomodoro instead of Presets because Shift+P is Pomodoro so I guess it detects Shift+P and does not go further.

**Comment by remvze** [comment]
> Follow back : they work but not all the time. I don't know how to reproduce but when I refresh, I can open Pomodoro, Notepad. I can never open Share Sounds modal.

I could reproduce a similar problem in Firefox using Alt + S for the Share modal; it would open the History menu of Firefox, and after closing it, no shortcut would work. Using Shift instead has fixed that problem for me.

**Comment by remvze** [comment]
> Yep so everything is fine except for the Shift+Alt+P which opens Pomodoro instead of Presets modal !

Unfortunately, I couldn't reproduce this issue. Is it consistent across devices and browsers?

> For screen readers, I guess we'll see that later, it is not like it is usable at the moment for people using screen readers anyway ! I am looking forward to help with this part of accessibility when I have taken my training course in June about it.

I've just improved aria labels for screen readers (some buttons are left, which I'll fix very soon), so the screen reader experience shouldn't be as bad anymore. But, as you mentioned, some keyboard behaviors become unpredictable. For example, when you focus on the favorite button and press Enter, instead of toggling the favorite state, it starts the sound itself.

> In the mean time, I wanted to say thanks for this app. It is a great app which I've been enjoying for a while now. I am thinking about buying you a coffee someday in the coming months too ! 

Thank you so much, I appreciate your kind words. Your contributions have been of great help to me and this project; improving accessibility has been on my checklist for a long time, and your contributions not only helped with accessibility but also pushed me to do more research and take it more seriously.

**Comment by SuperMeepBoy** [comment]
@remvze 

> Unfortunately, I couldn't reproduce this issue. Is it consistent across devices and browsers?
Just tried it on Firefox, it works. But it definitely does not work on LibreWolf. Shift+Maj+P opens Pomodoro. I guess it will stay this way as there must not be many users using LibreWolf.

> I've just improved aria labels for screen readers (some buttons are left, which I'll fix very soon), so the screen reader experience shouldn't be as bad anymore. But, as you mentioned, some keyboard behaviors become unpredictable. For example, when you focus on the favorite button and press Enter, instead of toggling the favorite state, it starts the sound itself.
I've seen that ! That is great !
Just to be sure, keyboard behaviors become unpredictable **with screen readers enabled** or even **without them enabled** ? Because, without screen reader enabled, pressing Enter while on Favorite button, works here (Firefox & LibreWolf).

> Thank you so much, I appreciate your kind words. Your contributions have been of great help to me and this project; improving accessibility has been on my checklist for a long time, and your contributions not only helped with accessibility but also pushed me to do more research and take it more seriously.
This is the first project I'm contributing too. I have very little knowledge of front so I also try to learn along with it. Speaking of which, I'm going to open an issue on something because I don't know how to fix it. I've been looking for a few hours now and I just can't. I guess I should learn more React. x)

**Comment by remvze** [comment]
> Just to be sure, keyboard behaviors become unpredictable with screen readers enabled or even without them enabled ?

With screen readers enabled.

**Comment by SuperMeepBoy** [comment]
@remvze Okay ! Then I can close this issue. It seems working overall, except on LibreWolf.
