### ISSUE TITLE
Bug with modals superposition

### ISSUE THREAD

**Issue by SuperMeepBoy** [remvze/moodist#28]
Steps :
1/ Shift + P to open Pomodoro
2/ Shift + N to open Notepad
3/ Write somthing in the notepad
4/ Press Esc.

Expected :
The Notepad modal is closed

Actual :
The Pomodoro modal in the background is closed

Additional comments :
For some reasons if you don't interact with the notepad modal (such as typing or deleting things), escape will correctly close the Notepad modal.

Solution :
Either a fix to detect which modal to close but maybe the question is "should we allow 2 modals to be opened at the same time ?".
I don't have an opinion about it because I don't know more about modals, sorry ! :)

**Comment by remvze** [comment]
Fixed it. It now allows only one modal at a time.
