### ISSUE TITLE
[Bug] Show more/Show less button disappear if we use them too quickly

### ISSUE THREAD

**Issue by SuperMeepBoy** [remvze/moodist#31]
Accidentally pressed 3 times the button in a row and discovered about it. If you trigger the Show less/Show more buttons with the keyboard too quickly, it disappears. See the screenshot below:

![image](https://github.com/remvze/moodist/assets/17031351/f0eb1fe9-6def-4682-bea8-449698611afb)

**Comment by remvze** [comment]
Thanks for reporting this issue; I've fixed it.
