### ISSUE TITLE
Sounds credit and license?

### ISSUE THREAD

**Issue by nclm** [remvze/moodist#33]
The website says “carefully curated” and the Github that everything is placed under MIT, but it feels like some source is missing for all the sounds, and a confirmation that they are for sure under MIT as well.

**Comment by remvze** [comment]
Hey there! All sounds are sourced from either [Pixabay](https://pixabay.com/) or [Freesound](https://freesound.org/), except for the binaural beats, which I created myself. The license for Pixabay [doesn't require crediting](https://pixabay.com/service/license-summary/), while for Freesound, I've only selected sounds with a [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), which also doesn't require crediting.

**Comment by nclm** [comment]
Sounds good thanks. Just in case other have the same questions, it could be worth considering adding this information somewhere, for instance the Github readme.

**Comment by remvze** [comment]
> Pixabay license is also not “free”, which means I’m not sure you can apply MIT on top of it.

Could you please specify which part of their license you are referring to?

**Comment by nclm** [comment]
Just the facts that there are clauses under “What are you not allowed to do with Content?”. They are fine to use in this project of course, but then when the only license mentioned in the root of the repo is MIT, a much more permissive license, it will be assumed that everything in the project repo is under MIT, which isn’t the case. Someone could fork or use sound clips from the project thinking they are under MIT. I’m not a license specialist at all so you might want to double check that, but to be on the safe side, mentioning that the contents of the sound effects folder are under other licenses could be worth?

**Comment by remvze** [comment]
Thank you for your suggestion. I've just included a license section in the README file. Could you please review it and confirm if this is what you meant?

**Comment by nclm** [comment]
Great, I think that’s clear :)
