### ISSUE TITLE
[Sound request] Washing machine

### ISSUE THREAD

**Issue by SuperMeepBoy** [remvze/moodist#34]
I wish I could listen to a washing machine. Ideally the sound is long enough to hear the different cycles of it.

I guess we can find one here : https://pixabay.com/sound-effects/search/washing%20machine/?duration=480- ? 🤔

**Comment by remvze** [comment]
Ideally under 4MB.

**Comment by remvze** [comment]
Hey there. The washing machine sound is now available under the Things category.
