### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by brentonmallen1** [remvze/moodist#35]
Is there a way to add auth to this for the self hosted use case?

**Comment by SuperMeepBoy** [comment]
@brentonmallen1 As far as I know, there is no authentication mechanism in Moodist (tho, I contribute on this for only a few days).

However, if you really want to do this (and as long as @remvze who is the creator of the code confirms there is not authentication mechanism), you could use basic HTTP Auth. If you use Nginx : https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

If you need help for this, let me know, I may be able to help.

**Comment by brentonmallen1** [comment]
Great suggestion, thank you!
