### ISSUE TITLE
[Feature Request] Ability to save presets

### ISSUE THREAD

**Issue by Nelinski** [remvze/moodist#6]
Great app, thanks for sharing (especially via docker). It would be great if you could save a number of presets to make it easier to use each time you open it. They would include:

- Ability to name the preset
- Ideally the ability to add a description to the preset
- Select what sounds you want included in the preset
- What volume level you want each sound at
- Any other features added in the future (e.g. if you add ability to change sound frequency)

**Comment by remvze** [comment]
Thank you! This is definitely on my checklist, and I'll begin working on it as soon as the sharing sounds feature is complete!

**Comment by remvze** [comment]
Hello there. This feature is now available!
